language: node_js
 node_js:
 - stable
 branches:
   only:
   - development
notifications:
    email:
      recipients:
        - conormcbride158@gmail.com     
        
      on_success: never        
      on_failure: always       