language: node_js

 script:
    - npm run coverage
 after_success:
    - npm run report-coverage
    branches:
      only:
      - development

 notifications:
    email:
      recipients:
        - conormcbride158@gmail.com     
        
      on_success: never        
      on_failure: always    