--- 
after_success: 
  - "npm run report-coverage"
branches: 
  only: 
    - development
language: node_js
node_js: 
  - stable
notifications: 
  email: 
    on_failure: always
    on_success: never
    recipients: 
      - conormcbride158@gmail.com
script: 
  - "npm run coverage"

      
      
  